accounts/urls.py
from django.urls import path

from . import views



app_name = 'accounts'

urlpatterns = [

    path('register/',views.register,name='register'),
    path('logout/',views.logoutuser,name='logout'),
    path('login/',views.loginpage,name='login'),

]

djangosite/urls.py
from django.contrib import admin
from django.urls import path,include


from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

posts/urls.py
from django.urls import path

from . import views
urlpatterns = [

    path('',views.home,name='home'),
    path('blog/',views.blog,name='blog'),
    path('search/',views.search,name='search'),
    path('blog/<str:id>/',views.post,name='detail'),
   
    
    
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class PostView(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey('Post',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username 

class Author(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    profile_picture = models.ImageField()

    def __str__(self):

        return self.user.username

class Category(models.Model):

    title = models.CharField(max_length=20) 

    def __str__(self):

        return self.title   


class Comment(models.Model):
    
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    post = models.ForeignKey('Post',related_name='comments',on_delete=models.CASCADE)

    def __str__(self):

        return self.user.username

class Post(models.Model):

    title = models.CharField(max_length=100)
    overview = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    #comment_count = models.IntegerField(default=0)
    #view_count = models.IntegerField(default=0)

    author = models.ForeignKey(Author,on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    category = models.ManyToManyField(Category)
    featured = models.BooleanField(default=False)


    def __str__(self):

        return self.title

    @property

    def comment_count(self):

        return Comment.objects.filter(post=self).count()    


    @property
    def view_count(self):
        return PostView.objects.filter(post=self).count()

    @property

    def get_comments(self):

        return self.comments.all().order_by('-timestamp')    




    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ValidationError





class CreateUserForm(UserCreationForm):
    
    class Meta:

        model = User
        fields = ['username','email','password1','password2']


    def clean_email(self):

    
        email = self.cleaned_data['email']

        if User.objects.filter(email=email).exists():



            raise ValidationError('this email already used')

        return email

    def clean_username(self):
        
        username = self.cleaned_data['username']

        if len(username) < 3 :
            raise ValidationError('your username length must greater than 2 char')

        return username     

posts/forms.py
from django import forms
from django.forms import ModelForm 
from .models import Comment





class CommentForm(forms.ModelForm):

    content =forms.CharField(widget=forms.Textarea(attrs={
        'class':'form-control',
        'placeholder':'type your comment',
        'id':'usercomment',
        'rows':'4'
    }))

    class Meta:
        model = Comment
        fields = ('content',)

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import AuthenticationForm 
from django.contrib import messages


from .forms import CreateUserForm

def register(request):
    
    form = CreateUserForm(request.POST or None)


    if request.method == 'POST':
        

        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            return redirect('accounts:login')


    context = {
        "form":form
    }        

    return render(request,'accounts/register.htm',context) 

def loginpage(request):
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password') 

        user = authenticate(request,username=username,password=password)

        if user is not None:
            login(request,user)
            return redirect('home') 

        else:

            messages.error(request,'username or password is incorrect')
           
    form = AuthenticationForm()
    context = {
        "form":form
    }
    return render(request,'accounts/login.htm',context)      

def logoutuser(request):
    logout(request)
    return redirect('home')    

posts/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
from django.db.models import Count,Q
from .models import Post,PostView
from .forms import CommentForm

def search(request):
    queryset = Post.objects.all()
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query) |
            Q(overview__icontains=query)
        ).distinct()
    context = {
        'queryset':queryset
    }    


    return render(request,'posts/search_result.htm',context)

def get_category_count():

    queryset = Post.objects.values('category__title').annotate(Count('category__title'))

    return queryset


def home(request):

    latest = Post.objects.order_by('-timestamp')[0:3]

    context = {
        
        'latest':latest,
    }

    return render(request,'posts/index.htm',context)

def blog(request):

    category_count = get_category_count()
    print(category_count)

    post_list = Post.objects.all()
    
    most_recent = Post.objects.order_by('-timestamp')[:3]
    
    
    context = {
        'post_list':post_list,
        'most_recent':most_recent,
        'category_count':category_count,
        
        
    }

    return render(request,'posts/blog.htm',context)

def post(request,id):



    post = get_object_or_404(Post,id=id)
    if request.user.is_authenticated:

    
        PostView.objects.get_or_create(user = request.user,post=post)
    form = CommentForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.instance.user = request.user
            form.instance.post = post
            form.save()

            return redirect(reverse('detail',kwargs={
                'id':post.id

            }))



    context = {
        'post':post,
        'form':form,
    }



    return render(request,'posts/detail.htm',context)    

accounts/templates/accounts/base.htm
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>




    

    

    <div class="container">

        {% block content %}

        {% endblock %}
       

    </div>

    
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
</body>
</html>

accounts/templates/accounts/login.htm
  
{% extends 'accounts/base.htm' %}

{% load crispy_forms_tags %}


{% block title %} Login {% endblock  %}
{% block content %}

<div class="container">
	<h1>Login</h1>
	<form method="POST" class="form">
	  {% csrf_token %}
	  {{form|crispy}}
	  
	<button type="submit" class="btn btn-primary">Login</button>
	  
	</form>
	<br>
	{% for message in messages %}

		<p id="message">{{message}}</p>

	{% endfor %}
	<div class="mt-4">
	  <div class="d-flex justify-content-center links">
		<p id='form-title'>Don't have an account?</p> <a href="{% url 'accounts:register' %}" class="ml-2">Register</a>
	  </div>
</div>


<a  class="btn btn-outline-dark" href="{% url 'home' %}">&#x2190; Back to Home</a>
{% endblock  %}

accounts/templates/accounts/register.htm
{% extends 'accounts/base.htm' %}

{% load crispy_forms_tags %}

{% block title %} Register {% endblock  %}

{% block content %}

    
<div class="container">
	<h1>Sign Up</h1>
	<form method="POST" class="form">
	  {% csrf_token %}
	  {{form|crispy}}
	  
		<button type="submit" class="btn btn-primary">Sign Up</button>
	  
	</form>
	<div class="mt-4">
	  <div class="d-flex justify-content-center links">
		<p id='form-title'>Already have an account? </p> <a href="{% url 'accounts:login' %}" class="ml-2">Login</a>
	  
	  </div>
	</div>
</div>
<a  class="btn btn-outline-dark" href="{% url 'home' %}">&#x2190; Back to Home</a>

{% endblock %}

posts/templates/posts/base.htm
{% load static %}
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Django blog </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Font Awesome CSS-->
   
    <!-- Custom icon font-->
    <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
    <!-- Google fonts - Open Sans-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Fancybox-->
    <link rel="stylesheet" href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    
    
  </head>
  

  <body>

    {% include 'posts/navbar.htm' %}

    {% block content %}

    {% endblock %}


    {% include 'posts/footer.htm' %}
    
    
    <!-- JavaScript files-->

    <script  src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script  src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
    <script  src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script  src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %} "> </script>
    <script  src="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %} "></script>
    <script  src="{% static 'js/front.js' %} "></script>
    
  


  </body>
</html>

posts/templates/posts/blog.htm
{% extends 'posts/base.htm' %}

{% load static %}




{% block content %}
<div class="container">
  <div class="row">
    <!-- Latest Posts -->
    <main class="posts-listing col-lg-8"> 
      <div class="container">
        <div class="row">
          {% for post in post_list %}
          <!-- post -->
          <div class="post col-xl-6">
            <div class="post-thumbnail"><a href="{% url 'detail' post.id %}"><img src="{{post.thumbnail.url}}" alt="..." class="img-fluid"></a></div>
            <div class="post-details">
              <div class="post-meta d-flex justify-content-between">
                <div class="date meta-last">{{post.timestamp}}</div>
                {% for cat in post.category.all %}
                <div class="category"><a href="#">{{cat}}</a></div>
                {% endfor  %}
              </div><a href="{% url 'detail' post.id %}">
                <h3 class="h4">{{post.title}}</h3></a>
              <p class="text-muted">{{post.overview}}</p>
              <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                  <div class="avatar"><img src="{{post.author.profile_picture.url}}" alt="..." class="img-fluid"></div>
                  <div class="title"><span>{{post.author.user.username}}</span></div></a>
                <div class="date"><i class="icon-clock"></i>{{post.timestamp|timesince}}</div>
                <div class="comments meta-last"><i class="icon-comment"></i>{{post.comment_count}}</div>
              </footer>
            </div>
          </div>
          <!-- post             -->
          {% endfor %}
        </div>
        
        <!-- Pagination -->
        
          
            
          
        
      </div>
    </main>
    <aside class="col-lg-4">
      <!-- Widget [Search Bar Widget]-->
      <div class="widget search">
        <header>
          <h3 class="h6">Search the blog</h3>
        </header>
        <form action="{% url 'search' %}" class="search-form">
          <div class="form-group">
            <input type="text" name="q" placeholder="What are you looking for?">
            <button type="submit" class="submit"><i class="icon-search"></i></button>
          </div>
        </form>
      </div>
      <!-- Widget [Latest Posts Widget]        -->
      <div class="widget latest-posts">
        <header>
          <h3 class="h6">Latest Posts</h3>
        </header>
        {% for post in most_recent %}
        <div class="blog-posts"><a href="{% url 'detail' post.id %}">
          
            <div class="item d-flex align-items-center">
              <div class="image"><img src="{{post.thumbnail.url}}" alt="..." class="img-fluid"></div>
              <div class="title"><strong>{{post.title}}</strong>
                <div class="d-flex align-items-center">
                  <div class="views"><i class="icon-eye"></i>{{post.view_count}}</div>
                  <div class="comments"><i class="icon-comment"></i>{{post.comment_count}}</div>
                </div>


                
              </div>



              
        </div>
        {% endfor %}
        
      </div>  
      <!-- Widget [Categories Widget]-->
      <div class="widget categories">
        <header>
          <h3 class="h6">Categories</h3>
        </header>
        {% for cat in category_count %}
        <div class="item d-flex justify-content-between"><a href="#">{{cat.category__title}}</a><span>{{cat.category__title__count}}</span></div>

        {% endfor %}
      </div>
      <!-- Widget [Tags Cloud Widget]-->
         
        
          
        
        
          
          
          
          
          
        
      
    </aside>
  </div>
</div>

{% endblock %}

posts/templates/posts/detail.htm
{% extends 'posts/base.htm'%}


{% load static %}


{% block content %}
<style>
    .post-body img {
      width: 100%;
    }
</style>

<div class="container">
    <div class="row">
      <!-- Latest Posts -->
      <main class="post blog-post col-lg-8"> 
        <div class="container">
          <div class="post-single">
            <div class="post-thumbnail"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></div>
            <div class="post-details">
              <div class="post-meta d-flex justify-content-between">
                <div class="category">
                  {% for cat in post.categories.all %}
                  <a href="#">{{ cat }}</a>
                  {% endfor %}
                </div>
                
              </div>
              <h1>{{ post.title }}<a href="#"><i class="fa fa-bookmark-o"></i></a></h1>
              <div class="post-footer d-flex align-items-center flex-column flex-sm-row"><a href="#" class="author d-flex align-items-center flex-wrap">
                  <div class="avatar"><img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid"></div>
                  <div class="title"><span>{{ post.author.user.username }}</span></div></a>
                <div class="d-flex align-items-center flex-wrap">       
                  <div class="date"><i class="icon-clock"></i> {{ post.timestamp|timesince }} ago</div>
                  <div class="views"><i class="icon-eye"></i>{{post.view_count}}</div>
                  <div class="comments meta-last"><i class="icon-comment"></i>{{post.comment_count}}</div>
                </div>
              </div>
          
            </div>
            <div class="post-body">
                {{ post.overview | safe }}
                
            </div>
            <div class="post-comments">
                  <header>

                    <h3 class="h6">Post Comments<span class="no-of-comments">({{ post.comments.count }})</span></h3>

                  </header>

                  {% for comment in post.get_comments %}
                  <div class="comment">
                    <div class="comment-header d-flex justify-content-between">
                      <div class="user d-flex align-items-center">
                        <div class="image">
                          {% if comment.user.author %}
                          <img src="{{ comment.user.author.profile_picture.url }}" alt="..." class="img-fluid rounded-circle ">
                          {% else %}
                          <img src="{% static 'images/user.svg' %}" alt="..." class="img-fluid rounded-circle">
                          {% endif %}
                        </div>
                        <div class="title"><strong>{{ comment.user.username }}</strong><span class="date">{{ comment.timestamp|timesince }} ago</span></div>
                      </div>
                    </div>
                    <div class="comment-body">
                      <p>{{ comment.content }}</p>
                      
                    </div>
                  </div>
                  {% endfor %}
            </div>
                {% if request.user.is_authenticated %}
                <div class="add-comment">
                  <header>
                    <h3 class="h6">Leave a reply</h3>
                  </header>
                  <form method="POST" action="." class="commenting-form">
                    {% csrf_token %}
                    <div class="row">
                      <div class="form-group col-md-12">
                        {{ form }}
                      </div>
                      <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-secondary">Submit Comment</button>
                      </div>
                    </div>
                  </form>
                </div>
                {% else %}
                <a href="{% url 'accounts:login' %}" class="btn btn-primary">Login to comment</a>
                {% endif %}
              </div>
            


          </div>
        </div>
      </main>
             
    </div>
</div>   

{% endblock %}

posts/templates/posts/footer.htm
{% load static %}
<footer class="main-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="logo">
              <h6 class="text-white">Mohammad Hosseini</h6>
            </div>
            <div class="contact-details">
              <p>Iran,Tehran</p>
              <p>Phone: 09351792964</p>
              <p>Email: <a href="mailto:mamadhssg@gmail.com">mamadhssg@gmail.com</a></p>
              <ul class="social-menu">
                
                
                
                <li class="list-inline-item"><a href="https://t.me/mamadhss"><i class="fa fa-telegram"></i></a></li>
                <li class="list-inline-item"><a href="https://github.com/mamadhss"><i class="fa fa-github"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="menus d-flex">
              <ul class="list-unstyled">
                <li>This site is built in Python & Django, jQuery & Bootstrap</li>
                
              </ul>
              
            </div>
          </div>

        </div>
      </div>
      <div class="copyrights">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <p>&copy; 2020. All rights reserved.</p>
            </div>
            <div class="col-md-6 text-right">
              <p>
                Django Blog
              </p>
            </div>
          </div>
        </div>
      </div>
</footer>

posts/templates/posts/index.htm
{% extends 'posts/base.htm' %}
{% load static %}




{% block content %}

<section style="background: url({% static 'images/python.jpg' %}); background-size: cover; background-position: center center" class="hero">
  <div class="container">
    <div class="row">
      <div class="col-lg-7">
        <h1></h1><a href="{% url 'blog' %}" class="hero-link">Discover More</a>
      </div>
    </div>
  </div>
</section>

    
    <!-- Intro Section-->
    


    
    
    <!-- Latest Posts -->
    <section class="latest-posts"> 
      <div class="container">
        <header> 
          <h2>Latest from the blog</h2>
          <p class="text-big"></p>
        </header>
        <div class="row">
            {% for obj in latest %}
            <div class="post col-md-4">
              <div class="post-thumbnail"><a href="{% url 'detail' obj.id %}"><img src="{{ obj.thumbnail.url }}" alt="..." class="img-fluid"></a></div>
              <div class="post-details">
                <div class="post-meta d-flex justify-content-between">
                  <div class="date">{{ obj.timestamp }}</div>
                  <div class="category">
                    {% for cat in obj.category.all %}
                    <a href="#">{{ cat }}</a>
                    {% endfor %}
                    </div>
                </div><a href="{% url 'detail' obj.id %}">
                  <h3 class="h4">{{ obj.title }}</h3></a>
                <p class="text-muted">{{ obj.overview|linebreaks|truncatechars:200 }}</p>
              </div>
            </div>
            {% endfor %}
          </div>
          
        </div>
    </section>
      
    <!-- Newsletter Section-->
    

{% endblock %}

posts/templates/posts/navbar.htm
<style>
  .hello-msg{
      font-size: 15px;
      color:red;
      margin-right: 9px;
      margin-top: 8px;

  }
  
</style>


    <header class="header">
      <!-- Main Navbar-->
      <nav class="navbar navbar-expand-lg">
        <div class="search-area">
          <div class="search-area-inner d-flex align-items-center justify-content-center">
            <div class="close-btn"><i class="icon-close"></i></div>
            <div class="row d-flex justify-content-center">
              <div class="col-md-8">
                <form action="{% url 'search' %}">
                  <div class="form-group">
                    <input type="search" name="q" id="search" placeholder="What are you looking for?">
                    <button type="submit" class="submit"><i class="icon-search-1"></i></button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between">
            <!-- Navbar Brand --><a href="{% url 'home' %}" class="navbar-brand">Django Blog</a>
            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
          </div>
          <!-- Navbar Menu -->
          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a href="{% url 'home' %}" class="nav-link active  ">Home</a>
              </li>
              <li class="nav-item"><a href="{% url 'blog' %}" class="nav-link ">Blog</a>
              </li>

              {% if user.is_authenticated %}
              
              <span class="hello-msg">Hello,{{request.user}}</span>
              <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link ">Logout</a>
              </li>
                    
              
              {% else %}

              <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
              </li>

              {% endif %}


            </ul>
            <div class="navbar-text"><a href="#" class="search-btn"><i class="icon-search-1"></i></a></div>
            
          </div>
        </div>
      </nav>
    </header>

posts/templates/posts/search_result.htm
{% extends 'posts/base.htm'%}

{% load static %}

{% block content %}

{% for post in queryset %}

    <a href="{% url 'detail' post.id %}">{{post.title}}</a>


{% endfor %}

{% endblock %}